In [1]:
# Notebook to read in a CSV of the scheds and output a 
# sched file and SQL insert statements
# JR - 2023
import sys
import os
import math
import teams

# The sched was obtained from https://www.espn.com/nfl/schedulegrid, 
# converted to CSV then processed into our sche file format.
# NOTE: In 2023 needed to temp change WAS to WSH and LVR to LV in teams.py

In [2]:
YEAR = 2024
SCHED_DIR = os.path.join(os.getcwd(), "scheds")
FILENAME = os.path.join(SCHED_DIR, f"sched_{YEAR}.csv")
SQL_FILENAME = os.path.join(SCHED_DIR, f"sched_{YEAR}.sql")
SCHED_FILENAME = os.path.join(SCHED_DIR, f"sched_{YEAR}.txt")

In [4]:
def do(year, filename, sql_filename, sched_filename):

    f = open(filename, 'r')
    lines = f.readlines()
    sched = {}
    
    year_abbr = str(year)[2:]

    #print("WSH: %d" % teams.name_to_num("WSH"))
    #print("ARI: %d" % teams.name_to_num("ARI"))

    for line in lines:
        #print(line)
        parts = line.rstrip().split()
        #print(parts[0] +  "," +  parts[17])

        home_name = parts[0]
        home_num = teams.name_to_num(parts[0])
        print(home_name, home_num)
        games = []
        
        # Need to stip any white spaces!
        for i in range(len(parts)):
            parts[i] = parts[i].strip()
        
        for opp in parts[1:]:

            away = False
            abbrev = opp
            if abbrev[:1] == '@':
                away = True
                abbrev = abbrev[1:]

            team_num = teams.name_to_num(abbrev)
            #print(abbrev, team_num)

            if(away == True):
                games.append(-team_num)
            else:
                games.append(team_num)

            sched[home_num] = games

        
    #print(sched)
    #print(len(sched))

    #print("%s      1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18"%year)
    print(sched)
    f_out = open(sql_filename, "w")
    for t in range(1,33):
        week = 0
        if t == 20:
            print(t)
            print(sched.keys())
            print(len(sched.keys()))
            print("HERE1")
            print(sched[20], sched[21])
        for opp in sched[t][:18]:
            week += 1
            if opp == 0:
                continue
            if t == 20:
                print("INSERT INTO scheds set year=%d, team=%d, week=%d, opponent=%d;"%(year, t, week,opp))
            f_out.write("INSERT INTO scheds set year=%d, team=%d, week=%d, opponent=%d;\n"%(year, t, week,opp))
    f_out.close()
            
        
    f_out = open(sched_filename, "w")
    print(f"{year}      1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18")
    f_out.write(f"{year}      1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18\n")
    for t in range(1,33):
        week = 0
        print(f"{teams.num_to_abbrev(t):4} {t:2} ", end='')
        f_out.write(f"{teams.num_to_abbrev(t):4} {t:2} ")
        for opp in sched[t][:18]:
            week += 1
            if week < 18:
                print(f"{opp:3},", end='')
                f_out.write(f"{opp:3},")
            else:
                print(f"{opp:3}", end='')
                f_out.write(f"{opp:3}")
        print("")
        f_out.write("\n")
    print("")
    f_out.write("\n")
    print("37526618227845253158164844313767")
    f_out.write("37526618227845253158164844313767\n")
    print("11211122222211211212121121111211")
    f_out.write("11211122222211211212121121111211\n")
        
        
    return

In [5]:
do(YEAR, FILENAME, SQL_FILENAME, SCHED_FILENAME)

ARI 23
ATL 1
BAL 6
BUF 3
CAR 29
CHI 4
CIN 5
CLE 31
DAL 7
DEN 8
DET 9
GB 10
HOU 32
IND 2
JAX 30
KC 12
LV 20
LAR 13
LAC 24
MIA 14
MIN 15
NE 16
NO 17
NYG 18
NYJ 19
PHI 21
PIT 22
SF 25
SEA 26
TB 27
TEN 11
WSH 28
{23: [-3, 13, 9, 28, -25, -10, 24, -14, 4, 19, 0, -26, -15, 26, 16, -29, -13, 25], 1: [22, -21, 12, 17, 27, -29, 26, -27, 7, -17, -8, 0, 24, -15, -20, 18, -28, 29], 6: [-12, 20, -7, 3, -5, 28, -27, -31, 8, 5, -22, -24, 21, 0, -18, 22, -32, 31], 3: [23, -14, 30, -6, -32, -19, 11, -26, 14, -2, 12, 0, 25, -13, -9, 16, 19, -16], 29: [-17, 24, -20, 5, -4, 1, -28, -8, 17, 18, 0, 12, 27, -21, 7, 23, -27, -1], 4: [11, -32, -2, 13, 29, 30, 0, -28, -23, 16, 10, 15, -9, -25, -15, 9, 26, -10], 5: [16, -12, 28, -29, 6, -18, -31, 21, 20, -6, -24, 0, 22, -7, -11, 31, 8, -22], 31: [7, -30, 18, -20, -28, -21, 5, 6, 24, 0, -17, 22, -8, -22, 12, -5, 14, -6], 7: [-31, 17, 6, -18, -22, 9, 0, -25, -1, 21, 32, -28, 18, 5, -29, 27, -21, 28], 8: [-26, 22, -27, -19, 20, 24, -17, 29, -6, -12, 1, -20, 31, 0, 2, -24, -5, 12], 9: [13, 27, -23, 26, 0, -7, -15, 11, -10, -32, 30, -2, 4, 10, 3, -4, -25, 15], 10: [-21, 2, -11, 15, -13, 23, 32, -30, 9, 0, -4, 25, 14, -9, -26, 17, -15, 4], 32: [-2, 4, -15, 30, 3, -16, -10, 2, -19, 9, -7, 11, -30, 0, 14, -12, 6, -11], 2: [32, -10, 4, 22, -30, -11, 14, -32, -15, 3, -19, 9, -16, 0, -8, 11, -18, 30], 30: [-14, 31, -3, -32, 2, -4, 16, 10, -21, 15, -9, 0, 32, -11, 19, -20, 11, -2], 12: [6, 5, -1, -24, 17, 0, -25, -20, 27, 8, -3, -29, 20, 24, -31, 32, -22, -8], 20: [-24, -6, 29, 31, -8, 22, -13, 12, -5, 0, -14, 8, -12, -27, 1, 30, -17, 24], 13: [-9, -23, 25, -4, 10, 0, 20, 15, -26, 14, -16, 21, -17, 3, -25, -19, 23, 26], 24: [20, -29, -22, 12, 0, -8, -23, 17, -31, 11, 5, 6, -1, -12, 27, 8, -16, -20], 14: [30, 3, -26, 11, -16, 0, -2, 23, -3, -13, 20, 16, -10, 19, -32, 25, -31, -19], 15: [-18, 25, 32, -10, 19, 0, 9, -13, 2, -30, -11, -4, 23, 1, 4, -26, 10, -9], 16: [-5, 26, -19, -25, 14, 32, -30, 19, -11, -4, 13, -14, 2, 0, -23, -3, 24, 3], 17: [29, -7, 21, -1, -12, 27, 8, -24, -29, 1, 31, 0, 13, -18, 28, -10, 20, -27], 18: [15, -28, -31, 7, -26, 5, 21, -22, 28, -29, 0, 27, -7, 17, 6, -1, 2, -21], 19: [-25, -11, 16, 8, -15, 3, -22, -16, 32, -23, 2, 0, 26, -14, -30, 13, -3, 14], 21: [10, 1, -17, -27, 0, 31, -18, -5, 30, -7, 28, -13, -6, 29, 22, -28, 7, 18], 22: [-1, -8, 24, -2, 7, -20, 19, 18, 0, -28, 6, -31, -5, 31, -21, -6, 12, 5], 25: [19, -15, -13, 16, 23, -26, 12, 7, 0, -27, 26, -10, -3, 4, 13, -14, 9, -23], 26: [8, -16, 14, -9, 18, 25, -1, 3, 13, 0, -25, 23, -19, -23, 10, 15, -4, -13], 27: [28, -9, 8, 21, -1, -17, 6, 1, -12, 25, 0, -18, -29, 20, -24, -7, 29, 17], 11: [-4, 19, 10, -14, 0, 2, -3, -9, 16, -24, 15, -32, -28, 30, 5, -2, -30, 32], 28: [-27, 18, -5, -23, 31, -6, 29, 4, -18, 22, -21, 7, 11, 0, -17, 21, 1, -7]}
20
dict_keys([23, 1, 6, 3, 29, 4, 5, 31, 7, 8, 9, 10, 32, 2, 30, 12, 20, 13, 24, 14, 15, 16, 17, 18, 19, 21, 22, 25, 26, 27, 11, 28])
32
HERE1
[-24, -6, 29, 31, -8, 22, -13, 12, -5, 0, -14, 8, -12, -27, 1, 30, -17, 24] [10, 1, -17, -27, 0, 31, -18, -5, 30, -7, 28, -13, -6, 29, 22, -28, 7, 18]
INSERT INTO scheds set year=2024, team=20, week=1, opponent=-24;
INSERT INTO scheds set year=2024, team=20, week=2, opponent=-6;
INSERT INTO scheds set year=2024, team=20, week=3, opponent=29;
INSERT INTO scheds set year=2024, team=20, week=4, opponent=31;
INSERT INTO scheds set year=2024, team=20, week=5, opponent=-8;
INSERT INTO scheds set year=2024, team=20, week=6, opponent=22;
INSERT INTO scheds set year=2024, team=20, week=7, opponent=-13;
INSERT INTO scheds set year=2024, team=20, week=8, opponent=12;
INSERT INTO scheds set year=2024, team=20, week=9, opponent=-5;
INSERT INTO scheds set year=2024, team=20, week=11, opponent=-14;
INSERT INTO scheds set year=2024, team=20, week=12, opponent=8;
INSERT INTO scheds set year=2024, team=20, week=13, opponent=-12;
INSERT INTO scheds set year=2024, team=20, week=14, opponent=-27;
INSERT INTO scheds set year=2024, team=20, week=15, opponent=1;
INSERT INTO scheds set year=2024, team=20, week=16, opponent=30;
INSERT INTO scheds set year=2024, team=20, week=17, opponent=-17;
INSERT INTO scheds set year=2024, team=20, week=18, opponent=24;
2024      1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
ATL   1  22,-21, 12, 17, 27,-29, 26,-27,  7,-17, -8,  0, 24,-15,-20, 18,-28, 29
IND   2  32,-10,  4, 22,-30,-11, 14,-32,-15,  3,-19,  9,-16,  0, -8, 11,-18, 30
BUF   3  23,-14, 30, -6,-32,-19, 11,-26, 14, -2, 12,  0, 25,-13, -9, 16, 19,-16
CHI   4  11,-32, -2, 13, 29, 30,  0,-28,-23, 16, 10, 15, -9,-25,-15,  9, 26,-10
CIN   5  16,-12, 28,-29,  6,-18,-31, 21, 20, -6,-24,  0, 22, -7,-11, 31,  8,-22
BAL   6 -12, 20, -7,  3, -5, 28,-27,-31,  8,  5,-22,-24, 21,  0,-18, 22,-32, 31
DAL   7 -31, 17,  6,-18,-22,  9,  0,-25, -1, 21, 32,-28, 18,  5,-29, 27,-21, 28
DEN   8 -26, 22,-27,-19, 20, 24,-17, 29, -6,-12,  1,-20, 31,  0,  2,-24, -5, 12
DET   9  13, 27,-23, 26,  0, -7,-15, 11,-10,-32, 30, -2,  4, 10,  3, -4,-25, 15
GB   10 -21,  2,-11, 15,-13, 23, 32,-30,  9,  0, -4, 25, 14, -9,-26, 17,-15,  4
TEN  11  -4, 19, 10,-14,  0,  2, -3, -9, 16,-24, 15,-32,-28, 30,  5, -2,-30, 32
KC   12   6,  5, -1,-24, 17,  0,-25,-20, 27,  8, -3,-29, 20, 24,-31, 32,-22, -8
LAR  13  -9,-23, 25, -4, 10,  0, 20, 15,-26, 14,-16, 21,-17,  3,-25,-19, 23, 26
MIA  14  30,  3,-26, 11,-16,  0, -2, 23, -3,-13, 20, 16,-10, 19,-32, 25,-31,-19
MIN  15 -18, 25, 32,-10, 19,  0,  9,-13,  2,-30,-11, -4, 23,  1,  4,-26, 10, -9
NE   16  -5, 26,-19,-25, 14, 32,-30, 19,-11, -4, 13,-14,  2,  0,-23, -3, 24,  3
NO   17  29, -7, 21, -1,-12, 27,  8,-24,-29,  1, 31,  0, 13,-18, 28,-10, 20,-27
NYG  18  15,-28,-31,  7,-26,  5, 21,-22, 28,-29,  0, 27, -7, 17,  6, -1,  2,-21
NYJ  19 -25,-11, 16,  8,-15,  3,-22,-16, 32,-23,  2,  0, 26,-14,-30, 13, -3, 14
LVR  20 -24, -6, 29, 31, -8, 22,-13, 12, -5,  0,-14,  8,-12,-27,  1, 30,-17, 24
PHI  21  10,  1,-17,-27,  0, 31,-18, -5, 30, -7, 28,-13, -6, 29, 22,-28,  7, 18
PIT  22  -1, -8, 24, -2,  7,-20, 19, 18,  0,-28,  6,-31, -5, 31,-21, -6, 12,  5
ARI  23  -3, 13,  9, 28,-25,-10, 24,-14,  4, 19,  0,-26,-15, 26, 16,-29,-13, 25
LAC  24  20,-29,-22, 12,  0, -8,-23, 17,-31, 11,  5,  6, -1,-12, 27,  8,-16,-20
SF   25  19,-15,-13, 16, 23,-26, 12,  7,  0,-27, 26,-10, -3,  4, 13,-14,  9,-23
SEA  26   8,-16, 14, -9, 18, 25, -1,  3, 13,  0,-25, 23,-19,-23, 10, 15, -4,-13
TB   27  28, -9,  8, 21, -1,-17,  6,  1,-12, 25,  0,-18,-29, 20,-24, -7, 29, 17
WAS  28 -27, 18, -5,-23, 31, -6, 29,  4,-18, 22,-21,  7, 11,  0,-17, 21,  1, -7
CAR  29 -17, 24,-20,  5, -4,  1,-28, -8, 17, 18,  0, 12, 27,-21,  7, 23,-27, -1
JAC  30 -14, 31, -3,-32,  2, -4, 16, 10,-21, 15, -9,  0, 32,-11, 19,-20, 11, -2
CLE  31   7,-30, 18,-20,-28,-21,  5,  6, 24,  0,-17, 22, -8,-22, 12, -5, 14, -6
HOU  32  -2,  4,-15, 30,  3,-16,-10,  2,-19,  9, -7, 11,-30,  0, 14,-12,  6,-11

37526618227845253158164844313767
11211122222211211212121121111211